### PR TITLE
Updated acq-models submodule, updated all sample and test data to ref…

### PR DESCRIPTION
**Pull request by komick**
…lect changes in phone_number

### CODE REVIEW

**Comment by komick** [comment]
Fixing ramp-cop errors

**Review by Bon2xl — APPROVED** [review]

**Review by craigmcnally — APPROVED** [review]
I understand this PR is for changes to the examples, but wanted to raise this point regardless...  Should we consider adding a pattern to limit what can go into the phone_number field?  For instance, does it make sense to allow `abcdefg` as a phone number?

**Review by craigmcnally — COMMENTED** [review]
We should probably resolve the ramlcop complaints while we're here...

**Comment by craigmcnally** [comment]
Ahhh WTF is going on?  sorry for the spam folks

**Pull request merged**
